movie_review/apps/login_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registration$', views.registration, name='registration'),
    url(r'^register$', views.create, name="create"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout")
]

movie_review/apps/movie_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^new$', views.new, name="new"),
    url(r'^watch$', views.watch, name="watch"),
    url(r'^create$', views.create, name="create"),
    url(r'^show/(?P<id>\d+)$', views.show, name="show"),
    url(r'^movie/(?P<id>\d+)$', views.showMovie, name="showMovie"),
    url(r'^delete/(?P<id>\d+)$', views.delete, name="delete"),
    url(r'^create_review/(?P<id>\d+)$', views.create_review, name="create_review"),
    url(r'^add$', views.add, name="add"),
    url(r'^add_outing$', views.add_outing, name="add_outing"),
    url(r'^outing/(?P<id>\d+)$', views.outing, name="outing"),
    url(r'^outing/join/(?P<id>\d+)$', views.outing_join, name="outing_join"),
    url(r'^cancel/(?P<id>\d+)$', views.cancel, name="cancel"),
    url(r'^delete/(?P<id>\d+)$', views.delete, name="delete"),
    url(r'^add_comment/(?P<id>\d+)$', views.add_comment, name="add_comment"),
    url(r'^delete_comment/(?P<id>\d+)$', views.delete_comment, name="delete_comment")
]

movie_review/movie_review/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.login_app.models import User
from apps.movie_app.models import Movie, Director, Review, Outing, Comment

class UserAdmin(admin.ModelAdmin):
    pass
admin.site.register(User, UserAdmin)

class DirectorAdmin(admin.ModelAdmin):
    pass
admin.site.register(Director, DirectorAdmin)

class MovieAdmin(admin.ModelAdmin):
    pass
admin.site.register(Movie, MovieAdmin)

class ReviewAdmin(admin.ModelAdmin):
    pass
admin.site.register(Review, ReviewAdmin)

class OutingAdmin(admin.ModelAdmin):
    pass
admin.site.register(Outing, OutingAdmin)

class CommentAdmin(admin.ModelAdmin):
    pass
admin.site.register(Comment, CommentAdmin)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_app.urls', namespace='users')),
    url(r'^movies/', include('apps.movie_app.urls', namespace='movies'))
]

movie_review/apps/movie_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_app.models import User
from datetime import datetime
import re

name_regex = re.compile(r"^[a-zA-Z\s]+$")

# Create your models here.
class DirectorManager(models.Manager):
    def director_validator(self, input):
        errors = []

        if len(input['new_director']) == 0:
            errors.append("Please enter a director")

        elif len(input['new_director']) < 5:
            errors.append("Director's name must have at least 5 characters")

        if not name_regex.match(input['new_director']):
            errors.append("Director's name must have letters only")

        if len(errors) == 0:
            # Director.objects.create(name=input['new_director'])
            return (True, ["Director input valid. Please fix other errors"])
        else:
            return (False, errors)

class Director(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = DirectorManager()

class MovieManager(models.Manager):
    def movie_validator(self, input):
        errors = []

        if len(input['movie']) == 0:
            errors.append("Please enter a movie")

        elif len(input['movie']) < 2:
            errors.append("Movie must have at least 2 characters")

        if len(errors) == 0:
            # Movie.objects.create(title=input['movie'], director=director)
            return (True, ["Movie input valid. Please fix other errors"])
        else:
            return (False, errors)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    director = models.ForeignKey(Director)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = MovieManager()

class ReviewManager(models.Manager):
    def review_validator(self, input):
        errors = []

        if len(input['description']) == 0:
            errors.append("Please enter a description")

        elif len(input['description']) < 5:
            errors.append("Description must be at least 5 characters. Be descriptive!")

        if not (input['rating']):
            errors.append("Please select a rating for this movie")

        if len(errors) == 0:
            # Review.objects.create(description=input['description'], rating=input['rating'])
            return (True, ["Review input valid. Please fix other errors"])
        else:
            return (False, errors)

class Review(models.Model):
    description = models.TextField()
    rating = models.IntegerField()
    user = models.ForeignKey(User)
    movie = models.ForeignKey(Movie)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()

class OutingManager(models.Manager):
    def outing_validator(self, input, user):
        errors = []

        if len(input['movie_out']) == 0 or len(input['location_out']) == 0 or len(input['theater_out']) == 0 or len(input['date_out']) == 0:
            errors.append("Please fill out all fields")

        if len(input['date_out']) > 0:
            start_date = datetime.strptime(input['date_out'], "%Y-%m-%d")

            if datetime.today() >= start_date:
                errors.append('Start date must be in the future')

        if len(errors) == 0:
            outing = Outing.objects.create(movie=input['movie_out'], location=input['location_out'], theater=input['theater_out'], date=start_date, user=user)
            outing.group.add(user)
            return (True, ["Successfully added movie outing to your schedule"])

        else:
            return (False, errors)

    def join_outing(self, id, user):
        outing = Outing.objects.get(id=id)
        outing.group.add(user)
        return (True, "Successfully added trip into your schedule")

class Outing(models.Model):
    movie = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    date = models.DateField()
    theater = models.CharField(max_length=100)
    user = models.ForeignKey(User)
    group = models.ManyToManyField(User, related_name="movie")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = OutingManager()

class CommentManager(models.Manager):
    def comment_validator(self, input, user, id):
        errors = []

        if len(input['comment']) < 1:
            errors.append("Please do not leave comment field blank")

        if len(errors) == 0:
            user = User.objects.get(id=user)
            outing = Outing.objects.get(id=id)
            text = Comment.objects.create(text=input['comment'], user=user, outing=outing)
            return (True, text, id)
        else:
            return (False, errors)

class Comment(models.Model):
    text = models.TextField(max_length=255)
    user = models.ForeignKey(User)
    outing = models.ForeignKey(Outing)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CommentManager()

movie_review/apps/movie_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse
from ..login_app.models import User
from .models import Director, Movie, Review, Outing, Comment
from django.contrib import messages

# Create your views here.

def index(request):
    if not 'user_id' in request.session:
        return redirect(reverse('users:index'))
    else:
        context = {
            "user": User.objects.get(id=request.session['user_id']),
            "movies": Movie.objects.all(),
            "reviews": Review.objects.all(),
        }
        return render(request, 'movie_app/index.html', context)

def new(request):
    if not 'user_id' in request.session:
        return redirect(reverse('users:index'))

    context = {
        "directors": Director.objects.all(),
        'user': User.objects.get(id=request.session['user_id']),
    }
    return render(request, 'movie_app/new.html', context)

def create(request):
    if request.method == 'POST':
        result_director = Director.objects.director_validator(request.POST)
        result_movie = Movie.objects.movie_validator(request.POST)
        result_review = Review.objects.review_validator(request.POST)
        if result_director[0] == False or result_movie[0] == False or result_review[0] == False:
            for error in result_director[1]:
                messages.error(request, error, extra_tags="director")
            for error in result_movie[1]:
                messages.error(request, error, extra_tags="movie")
            for error in result_review[1]:
                messages.error(request, error, extra_tags="review")
            return redirect(reverse('movies:new'))
        else:
            if 'new_director' in request.POST:
                director = Director.objects.create(name=request.POST['new_director'])
            else:
                director = Director.objects.get(id=request.POST['select_director'])

            movie = Movie.objects.create(title=request.POST['movie'], director=director)

            context = {
                'user': User.objects.get(id=request.session['user_id']),
                'movie': movie,
                'rating': request.POST['rating'],
                'description': request.POST['description'],
            }
            review = Review.objects.create(**context)

            return redirect(reverse('movies:index'))

def show(request, id):
    if not 'user_id' in request.session:
        return redirect(reverse('users:index'))

    reviews = Review.objects.filter(user_id=id)
    context = {
        'user': User.objects.get(id=id),
        'movie': Movie.objects.get(id=id),
        'reviews': reviews,
    }
    return render(request, 'movie_app/show.html', context)

def showMovie(request, id):
    if not 'user_id' in request.session:
        return redirect(reverse('users:index'))

    reviews = Review.objects.filter(movie_id=id)
    context = {
        'user': User.objects.get(id=request.session['user_id']),
        'movie': Movie.objects.get(id=id),
        'reviews': reviews,
    }
    return render(request, 'movie_app/showMovie.html', context)

def delete(request, id):
    Review.objects.get(id=id).delete()
    return redirect(reverse('movies:index'))

def create_review(request, id):
    if request.method == 'POST':
        context = {
            'user': User.objects.get(id=request.session['user_id']),
            'movie': Movie.objects.get(id=id),
            'rating': request.POST['rating'],
            'description': request.POST['description'],
        }

        review = Review.objects.create(**context)
        return redirect(reverse('movies:showMovie', kwargs={'id':review.movie.id}))

def watch(request):
    if not 'user_id' in request.session:
        return redirect(reverse('users:index'))

    user = User.objects.get(id=request.session['user_id'])
    context = {
        'user': user,
        'outings': Outing.objects.all().filter(group=user),
        'users': Outing.objects.all().exclude(group=user),

    }
    return render(request, 'movie_app/watch.html', context)

def add(request):
    if not 'user_id' in request.session:
        return redirect(reverse('users:index'))

    context = {
        'user': User.objects.get(id=request.session['user_id']),
    }
    return render(request, 'movie_app/add_outing.html', context)

def add_outing(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.session['user_id'])
        result = Outing.objects.outing_validator(request.POST, user)

        if result[0] == True:
            messages.success(request, result[1])
            return redirect(reverse('movies:watch'))
        else:
            for error in result[1]:
                messages.error(request, error, extra_tags="outing")
            return redirect(reverse('movies:add'))
    return redirect(reverse('movies:watch'))

def outing(request, id):
    if not 'user_id' in request.session:
        return redirect(reverse('users:index'))

    outing = Outing.objects.get(id=id)
    comments = Comment.objects.filter(outing=outing)
    context = {
        'user': User.objects.get(id=request.session['user_id']),
        'outing': outing,
        'groups': outing.group.all(),
        'comments': comments,
    }
    return render(request, 'movie_app/outing.html', context)


def outing_join(request, id):
    user = User.objects.get(id=request.session['user_id'])
    result = Outing.objects.join_outing(id, user)
    messages.success(request, result[1])
    return redirect(reverse('movies:watch'))

def cancel(request, id):
    user = User.objects.get(id=request.session['user_id'])
    outing = Outing.objects.get(id=id)
    outing.group.remove(user)
    messages.success(request, "Successfully Cancelled")
    return redirect(reverse('movies:watch'))

def delete(request, id):
    Outing.objects.get(id=id).delete()
    messages.success(request, "Successfully Deleted")
    return redirect(reverse('movies:watch'))

def add_comment(request, id):
    if request.method == 'POST':
        result = Comment.objects.comment_validator(request.POST, request.session['user_id'], id)

        if result[0] == True:
            messages.success(request, "Successfully added comment")
            return redirect(reverse('movies:outing', kwargs={'id': id}))
        else:
            for errors in result[1]:
                messages.error(request, errors, extra_tags="comments")
                return redirect(reverse('movies:outing', kwargs={'id': id}))

def delete_comment(request, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    msg = messages.success(request, "Successfully Deleted Comment")
    return redirect(reverse('movies:outing', kwargs={'id':comment.outing.id}))

movie_review/apps/movie_app/templates/movie_app/add_outing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Add a Movie Night Out</title>
    <!--load bootstrap here-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">
      <h1></h1>
      <a class="btn btn-primary" href="{% url 'movies:index' %}">Home</a>
      <a class="btn btn-info" href="{% url 'movies:new' %}">Add Movie and Review</a>
      <a class="btn btn-info" href="{% url 'movies:show' user.id %}">Your Reviews</a>
      <a class="btn btn-success" href="{% url 'movies:watch' %}">Watch Movie</a>
      <a class="btn btn-success" href="{% url 'movies:add' %}">Add a Movie Night Out</a>
      <a class="btn btn-danger" href="{% url 'users:logout' %}">Log Out</a>


      <h1>Add a Movie Night Out Here</h1>

      {% if messages %}
        {% for message in messages %}
          {% if "outing" in message.tags %}
            <li>{{message}}</li>
          {% endif %}
        {% endfor %}
      {% endif %}

      <form class="form-horizontal" action="{% url 'movies:add_outing' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label class="col-sm-2 control-label">Movie:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" name="movie_out" placeholder="Enter Movie Here">
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Location:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" name="location_out" placeholder="Enter Location Here">
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Theater:</label>
          <div class="col-sm-4">
            <input type="text" class="form-control" name="theater_out" placeholder="Enter Theater Here">
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Date:</label>
          <div class="col-sm-4">
            <input type="date" class="form-control" name="date_out" placeholder="Enter Date Here">
          </div>
        </div>

        <a class="btn btn-info" href="{% url 'movies:watch' %}">Go Back</a>
        <input type="submit" class="btn btn-info" value="Add Movie">

    </div>
  </body>
</html>

movie_review/apps/movie_app/templates/movie_app/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Movie Reviews Dashboard</title>
    <!--load bootstrap here-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'movie_app/css/style.css' %}" charset="utf-8">

  </head>
  <body>
    <div class="container">
      <h1 style="text-align:center">WELCOME {{user.first_name}} {{user.last_name}}</h1>
      <h4 class="waver">👋</h4>

      <a class="btn btn-primary" href="{% url 'movies:index' %}">Home</a>
      <a class="btn btn-info" href="{% url 'movies:new' %}">Add Movie and Review</a>
      <a class="btn btn-info" href="{% url 'movies:show' user.id %}">Your Reviews</a>
      <a class="btn btn-success" href="{% url 'movies:watch' %}">Watch Movie</a>
      <a class="btn btn-success" href="{% url 'movies:add' %}">Add a Movie Night Out</a>
      <a class="btn btn-danger" href="{% url 'users:logout' %}">Log Out</a>

      <h2>Recent Movie Reviews</h2>
      <hr>

      {% for review in reviews %}
        <h3><a href="{% url 'movies:showMovie' id=review.movie.id %}">{{review.movie.title}}</a></h3>
        <h4>Rating: {{review.rating}}</h4>
        <h4><a href="{% url 'movies:show' id=review.user.id %}">{{review.user.first_name}}</a> says: {{review.description}}<h4>
        <h5>Posted on {{review.created_at}}</h5>
        {% if review.user.id == request.session.user_id %}
          <a class="btn btn-danger" href="{% url 'movies:delete' id=review.id %}">Delete</a>
        {% endif %}
        <hr>
      {% endfor %}

    </div>
  </body>
</html>

movie_review/apps/movie_app/templates/movie_app/outing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Show Outing</title>
    <!--load bootstrap here-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>

    <div class="container">
      <h1></h1>
      <a class="btn btn-primary" href="{% url 'movies:index' %}">Home</a>
      <a class="btn btn-info" href="{% url 'movies:new' %}">Add Movie and Review</a>
      <a class="btn btn-info" href="{% url 'movies:show' user.id %}">Your Reviews</a>
      <a class="btn btn-success" href="{% url 'movies:watch' %}">Watch Movie</a>
      <a class="btn btn-success" href="{% url 'movies:add' %}">Add a Movie Night Out</a>
      <a class="btn btn-danger" href="{% url 'users:logout' %}">Log Out</a>

      {% if outing %}
      <h1>Movie: {{outing.movie}}</h1>
      <h3>Planned By: {{outing.user.first_name}} {{outing.user.last_name}}</h3>
      <h3>Location: {{outing.location}}</h3>
      <h3>Date: {{outing.date}}</h3>
      <h3>Theater: {{outing.theater}}</h3>
      {% endif %}

      <h1>Everyone in this outing:<h1>
        {% for group in groups %}
          <h3>{{group.first_name}} {{group.last_name}}</h3>
        {% endfor %}
      <br>

      {% if messages %}
        {% for message in messages %}
          {% if "comments" in message.tags %}
            <li>{{message}}</li>
          {% endif %}
        {% endfor %}
      {% endif %}

      <h1>Comments:</h1>
        <form class="form-horizontal" action="{% url 'movies:add_comment' id=outing.id %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label class="col-sm-1 control-label">Comment:</label>
            <div class="col-sm-4">
              <textarea class="form-control" name="comment"></textarea>
            </div>
          </div>
          <a class="btn btn-info" href="{% url 'movies:watch' %}">Go Back</a>
          <input type="submit" class="btn btn-info" value="Add Comment">
        </form>
      <h1></h1>

      {% for comment in comments %}
        <h3>{{comment.user.first_name}} says: {{comment.text}}</h3>
        <h4>Posted on: {{comment.created_at}}</h4>
        {% if user == comment.user %}
        <a class="btn btn-danger" href="{% url 'movies:delete_comment' id=comment.id %}">Delete Comment</a>
        {% endif %}
        <hr>
      {% endfor %}
    </div>
  </body>
</html>

movie_review/apps/movie_app/templates/movie_app/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Your Profile</title>
    <!--load bootstrap here-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">
      <h1>Your Info</h1>
      <a class="btn btn-primary" href="{% url 'movies:index' %}">Home</a>
      <a class="btn btn-info" href="{% url 'movies:new' %}">Add Movie and Review</a>
      <a class="btn btn-info" href="{% url 'movies:show' user.id %}">Your Reviews</a>
      <a class="btn btn-success" href="{% url 'movies:watch' %}">Watch Movie</a>
      <a class="btn btn-success" href="{% url 'movies:add' %}">Add a Movie Night Out</a>
      <a class="btn btn-danger" href="{% url 'users:logout' %}">Log Out</a>

      <h1>Name: {{user.first_name}} {{user.last_name}}</h1>
      <h3>Email: {{user.email}}</h3>

      <h2>Posted Reviews on the following movies: </h2>
      {% for review in reviews %}
        {% if review.user.id == user.id %}
        <h3>&nbsp;&nbsp;<a href="{% url 'movies:showMovie' review.movie.id %}">{{review.movie.title}}</a></h3>
        {% endif %}
      {% endfor %}
    </div>
  </body>
</html>

movie_review/apps/movie_app/templates/movie_app/showMovie.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Movie Chat</title>
    <!--load bootstrap here-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'movie_app/css/style.css' %}" charset="utf-8">
  </head>
  <body>
    <div class="container">
      <a class="btn btn-primary" href="{% url 'movies:index' %}">Home</a>
      <a class="btn btn-info" href="{% url 'movies:new' %}">Add Movie and Review</a>
      <a class="btn btn-info" href="{% url 'movies:show' user.id %}">Your Reviews</a>
      <a class="btn btn-success" href="{% url 'movies:watch' %}">Watch Movie</a>
      <a class="btn btn-success" href="{% url 'movies:add' %}">Add a Movie Night Out</a>
      <a class="btn btn-danger" href="{% url 'users:logout' %}">Log Out</a>

      <h1>{{movie.title}}</h1>
      <h3>Director: {{movie.director.name}}</h3>

      <h1>Reviews:</h1>
      <hr>

      {% for review in reviews %}
        <h3>Rating: {{review.rating}}</h3>
        <h3><a href="{% url 'movies:show' id=review.user.id %}">{{review.user.first_name}}</a> says: {{review.description}}</h3>
        <h5>Posted on {{review.created_at}}</h5>
        {% if review.user.id == request.session.user_id %}
          <a class="btn btn-danger" href="{% url 'movies:delete' id=review.id %}">Delete</a>
        {% endif %}
        <hr>
      {% endfor %}

      <br>
      <h2>Add a New Review:</h2>
      <form class="form-horizontal" action="{% url 'movies:create_review' id=movie.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label class="col-sm-2 control-label">Review:</label>
          <div class="col-sm-4">
            <textarea class="form-control" name="description"></textarea>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Movie Rating:</label>
          <div class="col-sm-4">
            <select class="form-control" name="rating">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
          </div>
        </div>
        <input style="margin-left:38%" type="submit" class="btn btn-info" value="Submit Review">
      </form>
    </div>
  </body>
</html>

movie_review/apps/movie_app/templates/movie_app/watch.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Watch a Movie</title>
    <!--load bootstrap here-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>

    <div class="container">
      <h1>Watch a Movie</h1>
      <a class="btn btn-primary" href="{% url 'movies:index' %}">Home</a>
      <a class="btn btn-info" href="{% url 'movies:new' %}">Add Movie and Review</a>
      <a class="btn btn-info" href="{% url 'movies:show' user.id %}">Your Reviews</a>
      <a class="btn btn-success" href="{% url 'movies:watch' %}">Watch Movie</a>
      <a class="btn btn-success" href="{% url 'movies:add' %}">Add a Movie Night Out</a>
      <a class="btn btn-danger" href="{% url 'users:logout' %}">Log Out</a>

      <h1>Your Plans</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Planner</th>
            <th>Movie</th>
            <th>Location</th>
            <th>Date</th>
            <th>Theater</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for outing in outings %}
          <tr>
            <td>{{outing.user.first_name}} {{outing.user.last_name}}</td>
            <td><a href="{% url 'movies:outing' outing.id %}">{{outing.movie}}</a></td>
            <td>{{outing.location}}</td>
            <td>{{outing.date}}</td>
            <td>{{outing.theater}}</td>
            {% if user == outing.user %}
            <td><a href="{% url 'movies:delete' outing.id %}">Delete</a></td>
            {% else %}
            <td><a href="{% url 'movies:cancel' outing.id %}">Leave This Group</a></td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <h1>Plans Available</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Planner</th>
            <th>Movie</th>
            <th>Location</th>
            <th>Date</th>
            <th>Theater</th>
            <th>Join?</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <td>{{user.user.first_name}} {{user.user.last_name}}</td>
            <td><a href="{% url 'movies:outing' user.id %}">{{user.movie}}</a></td>
            <td>{{user.location}}</td>
            <td>{{user.date}}</td>
            <td>{{user.theater}}</td>
            <td><a href="{% url 'movies:outing_join' user.id %}">Join This Group</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
  </body>
</html>